import React, { useState } from "react";
import { StatusBadge } from "../../../../shared/Status-Badge/status-badge";
import { DataTable } from "../../../../shared/Table/data-table";
import { MdOutlineMenuBook } from "react-icons/md";

const OrderManagement = () => {
  const ordersData = [
    {
      id: "0081727",
      customer: "Chinedu Okafor",
      email: "olivia@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "NEW",
      orderStatusVariant: "new",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Amina Bello",
      email: "phoenix@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "SUCCESSFUL",
      orderStatusVariant: "success",
      paymentStatus: "PROCESSING",
      paymentStatusVariant: "processing",
    },
    {
      id: "0081727",
      customer: "Emeka Nwosu",
      email: "lana@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "IN PROGRESS",
      orderStatusVariant: "progress",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Fatima Abubakar",
      email: "demi@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PENDING",
      paymentStatusVariant: "pending",
    },
    {
      id: "0081727",
      customer: "Tunde Adeyemi",
      email: "candice@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "IN PROGRESS",
      orderStatusVariant: "progress",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ngozi Ibe",
      email: "natali@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "CANCELLED",
      orderStatusVariant: "cancelled",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ifeoma Uche",
      email: "drew@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Kelechi Eze",
      email: "orlando@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Zainab Ibrahim",
      email: "andi@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "SUCCESSFUL",
      orderStatusVariant: "success",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Chijioke Obi",
      email: "kate@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Chinedu Okafor",
      email: "olivia@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "NEW",
      orderStatusVariant: "new",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Amina Bello",
      email: "phoenix@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "SUCCESSFUL",
      orderStatusVariant: "success",
      paymentStatus: "PROCESSING",
      paymentStatusVariant: "processing",
    },
    {
      id: "0081727",
      customer: "Emeka Nwosu",
      email: "lana@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "IN PROGRESS",
      orderStatusVariant: "progress",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Fatima Abubakar",
      email: "demi@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PENDING",
      paymentStatusVariant: "pending",
    },
    {
      id: "0081727",
      customer: "Tunde Adeyemi",
      email: "candice@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "IN PROGRESS",
      orderStatusVariant: "progress",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ngozi Ibe",
      email: "natali@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "CANCELLED",
      orderStatusVariant: "cancelled",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ifeoma Uche",
      email: "drew@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ndu Eze",
      email: "orlando@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Zainab Ibrahim",
      email: "andi@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "SUCCESSFUL",
      orderStatusVariant: "success",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Chijioke Obi",
      email: "kate@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Chinedu Okafor",
      email: "olivia@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "NEW",
      orderStatusVariant: "new",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Amina Bello",
      email: "phoenix@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "SUCCESSFUL",
      orderStatusVariant: "success",
      paymentStatus: "PROCESSING",
      paymentStatusVariant: "processing",
    },
    {
      id: "0081727",
      customer: "Emeka Nwosu",
      email: "lana@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "IN PROGRESS",
      orderStatusVariant: "progress",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Fatima Abubakar",
      email: "demi@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PENDING",
      paymentStatusVariant: "pending",
    },
    {
      id: "0081727",
      customer: "Tunde Adeyemi",
      email: "candice@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "IN PROGRESS",
      orderStatusVariant: "progress",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ngozi Ibe",
      email: "natali@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "CANCELLED",
      orderStatusVariant: "cancelled",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ifeoma Uche",
      email: "drew@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Kelechi Eze",
      email: "orlando@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Zainab Ibrahim",
      email: "andi@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "SUCCESSFUL",
      orderStatusVariant: "success",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Chijioke Obi",
      email: "kate@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Chinedu Okafor",
      email: "olivia@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "NEW",
      orderStatusVariant: "new",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Amina Bello",
      email: "phoenix@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "SUCCESSFUL",
      orderStatusVariant: "success",
      paymentStatus: "PROCESSING",
      paymentStatusVariant: "processing",
    },
    {
      id: "0081727",
      customer: "Emeka Nwosu",
      email: "lana@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "IN PROGRESS",
      orderStatusVariant: "progress",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Fatima Abubakar",
      email: "demi@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PENDING",
      paymentStatusVariant: "pending",
    },
    {
      id: "0081727",
      customer: "Tunde Adeyemi",
      email: "candice@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "IN PROGRESS",
      orderStatusVariant: "progress",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ngozi Ibe",
      email: "natali@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "CANCELLED",
      orderStatusVariant: "cancelled",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ifeoma Uche",
      email: "drew@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ndu Eze",
      email: "orlando@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Zainab Ibrahim",
      email: "andi@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "SUCCESSFUL",
      orderStatusVariant: "success",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Chijioke Obi",
      email: "kate@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Chinedu Okafor",
      email: "olivia@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "NEW",
      orderStatusVariant: "new",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Amina Bello",
      email: "phoenix@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "SUCCESSFUL",
      orderStatusVariant: "success",
      paymentStatus: "PROCESSING",
      paymentStatusVariant: "processing",
    },
    {
      id: "0081727",
      customer: "Emeka Nwosu",
      email: "lana@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "IN PROGRESS",
      orderStatusVariant: "progress",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Fatima Abubakar",
      email: "demi@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PENDING",
      paymentStatusVariant: "pending",
    },
    {
      id: "0081727",
      customer: "Tunde Adeyemi",
      email: "candice@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "IN PROGRESS",
      orderStatusVariant: "progress",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ngozi Ibe",
      email: "natali@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "CANCELLED",
      orderStatusVariant: "cancelled",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ifeoma Uche",
      email: "drew@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Kelechi Eze",
      email: "orlando@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Zainab Ibrahim",
      email: "andi@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "SUCCESSFUL",
      orderStatusVariant: "success",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Chijioke Obi",
      email: "kate@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Chinedu Okafor",
      email: "olivia@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "NEW",
      orderStatusVariant: "new",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Amina Bello",
      email: "phoenix@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "SUCCESSFUL",
      orderStatusVariant: "success",
      paymentStatus: "PROCESSING",
      paymentStatusVariant: "processing",
    },
    {
      id: "0081727",
      customer: "Emeka Nwosu",
      email: "lana@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "IN PROGRESS",
      orderStatusVariant: "progress",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Fatima Abubakar",
      email: "demi@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PENDING",
      paymentStatusVariant: "pending",
    },
    {
      id: "0081727",
      customer: "Tunde Adeyemi",
      email: "candice@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "IN PROGRESS",
      orderStatusVariant: "progress",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ngozi Ibe",
      email: "natali@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "CANCELLED",
      orderStatusVariant: "cancelled",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ifeoma Uche",
      email: "drew@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ndu Eze",
      email: "orlando@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Zainab Ibrahim",
      email: "andi@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "SUCCESSFUL",
      orderStatusVariant: "success",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Chijioke Obi",
      email: "kate@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Chinedu Okafor",
      email: "olivia@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "NEW",
      orderStatusVariant: "new",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Amina Bello",
      email: "phoenix@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "SUCCESSFUL",
      orderStatusVariant: "success",
      paymentStatus: "PROCESSING",
      paymentStatusVariant: "processing",
    },
    {
      id: "0081727",
      customer: "Emeka Nwosu",
      email: "lana@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "IN PROGRESS",
      orderStatusVariant: "progress",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Fatima Abubakar",
      email: "demi@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PENDING",
      paymentStatusVariant: "pending",
    },
    {
      id: "0081727",
      customer: "Tunde Adeyemi",
      email: "candice@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "IN PROGRESS",
      orderStatusVariant: "progress",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ngozi Ibe",
      email: "natali@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "CANCELLED",
      orderStatusVariant: "cancelled",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ifeoma Uche",
      email: "drew@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Kelechi Eze",
      email: "orlando@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Zainab Ibrahim",
      email: "andi@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "SUCCESSFUL",
      orderStatusVariant: "success",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Chijioke Obi",
      email: "kate@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Chinedu Okafor",
      email: "olivia@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "NEW",
      orderStatusVariant: "new",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Amina Bello",
      email: "phoenix@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "SUCCESSFUL",
      orderStatusVariant: "success",
      paymentStatus: "PROCESSING",
      paymentStatusVariant: "processing",
    },
    {
      id: "0081727",
      customer: "Emeka Nwosu",
      email: "lana@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "IN PROGRESS",
      orderStatusVariant: "progress",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Fatima Abubakar",
      email: "demi@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PENDING",
      paymentStatusVariant: "pending",
    },
    {
      id: "0081727",
      customer: "Tunde Adeyemi",
      email: "candice@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "IN PROGRESS",
      orderStatusVariant: "progress",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ngozi Ibe",
      email: "natali@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "CANCELLED",
      orderStatusVariant: "cancelled",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ifeoma Uche",
      email: "drew@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Ndu Eze",
      email: "orlando@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Zainab Ibrahim",
      email: "andi@untitledui.com",
      serviceType: "Quick Pickup",
      orderStatus: "SUCCESSFUL",
      orderStatusVariant: "success",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
    {
      id: "0081727",
      customer: "Chijioke Obi",
      email: "kate@untitledui.com",
      serviceType: "Normal/Express",
      orderStatus: "COMPLETED",
      orderStatusVariant: "completed",
      paymentStatus: "PAID",
      paymentStatusVariant: "paid",
    },
  ];

  const orderColumns = [
    { key: "id", title: "Order ID" },
    { key: "customer", title: "Customer Name" },
    { key: "email", title: "Email address" },
    { key: "serviceType", title: "Service Type" },
    {
      key: "orderStatus",
      title: "Order Status",
      render: (value, row) => (
        <StatusBadge status={value} variant={row.orderStatusVariant} />
      ),
    },
    {
      key: "paymentStatus",
      title: "Payment Status",
      render: (value, row) => (
        <StatusBadge status={value} variant={row.paymentStatusVariant} />
      ),
    },
  ];

  const [currentPage, setCurrentPage] = useState(1);

  const onPageChange = (newPage) => {
    setCurrentPage(newPage);
  };
  return (
    <div>
      <h2 className="text-2xl font-bold mb-11 flex items-center ">
        OrderManagement
        {/* <span className="flex items-center ml-2.5 gap-2 font-light text-white text-[16px] px-3 py-2 rounded-full bg-[#F32749]  ">
          <MdOutlineMenuBook size={16} />
          {ordersData.length}
        </span> */}
      </h2>
      <div>
        <DataTable
          columns={orderColumns}
          showFooter={true}
          data={ordersData}
          currentPage={currentPage}
          onPageChange={onPageChange}
          actionColumn={{
            title: "",
            render: (row) => (
              <a href="#" className="text-[#e86317] text-sm hover:underline">
                View Details
              </a>
            ),
          }}
          onRowClick={(row) => console.log("Row clicked:", row)}
        />
      </div>
    </div>
  );
};

export default OrderManagement;
